// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod swarmclaw_plugin {

    pub enum PluginRequestOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct PluginRequest<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for PluginRequest<'a> {
        type Inner = PluginRequest<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> PluginRequest<'a> {
        pub const VT_TOOL_NAME: ::flatbuffers::VOffsetT = 4;
        pub const VT_ARGUMENTS_JSON: ::flatbuffers::VOffsetT = 6;
        pub const VT_BINARY_PAYLOAD: ::flatbuffers::VOffsetT = 8;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            PluginRequest { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args PluginRequestArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<PluginRequest<'bldr>> {
            let mut builder = PluginRequestBuilder::new(_fbb);
            if let Some(x) = args.binary_payload {
                builder.add_binary_payload(x);
            }
            if let Some(x) = args.arguments_json {
                builder.add_arguments_json(x);
            }
            if let Some(x) = args.tool_name {
                builder.add_tool_name(x);
            }
            builder.finish()
        }

        /// The specific tool the host wants the plugin to execute
        #[inline]
        pub fn tool_name(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<&str>>(PluginRequest::VT_TOOL_NAME, None)
            }
        }
        /// The JSON arguments generated by the LLM
        #[inline]
        pub fn arguments_json(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                    PluginRequest::VT_ARGUMENTS_JSON,
                    None,
                )
            }
        }
        /// Optional raw binary payload (Zero-copy for images/video)
        #[inline]
        pub fn binary_payload(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                        PluginRequest::VT_BINARY_PAYLOAD,
                        None,
                    )
            }
        }
    }

    impl ::flatbuffers::Verifiable for PluginRequest<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                    "tool_name",
                    Self::VT_TOOL_NAME,
                    false,
                )?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                    "arguments_json",
                    Self::VT_ARGUMENTS_JSON,
                    false,
                )?
                .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                    "binary_payload",
                    Self::VT_BINARY_PAYLOAD,
                    false,
                )?
                .finish();
            Ok(())
        }
    }
    pub struct PluginRequestArgs<'a> {
        pub tool_name: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub arguments_json: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub binary_payload: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    }
    impl<'a> Default for PluginRequestArgs<'a> {
        #[inline]
        fn default() -> Self {
            PluginRequestArgs {
                tool_name: None,
                arguments_json: None,
                binary_payload: None,
            }
        }
    }

    pub struct PluginRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PluginRequestBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_tool_name(&mut self, tool_name: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                PluginRequest::VT_TOOL_NAME,
                tool_name,
            );
        }
        #[inline]
        pub fn add_arguments_json(&mut self, arguments_json: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                PluginRequest::VT_ARGUMENTS_JSON,
                arguments_json,
            );
        }
        #[inline]
        pub fn add_binary_payload(
            &mut self,
            binary_payload: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
        ) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                PluginRequest::VT_BINARY_PAYLOAD,
                binary_payload,
            );
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> PluginRequestBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            PluginRequestBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<PluginRequest<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for PluginRequest<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("PluginRequest");
            ds.field("tool_name", &self.tool_name());
            ds.field("arguments_json", &self.arguments_json());
            ds.field("binary_payload", &self.binary_payload());
            ds.finish()
        }
    }
    pub enum PluginResponseOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct PluginResponse<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for PluginResponse<'a> {
        type Inner = PluginResponse<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> PluginResponse<'a> {
        pub const VT_SUCCESS: ::flatbuffers::VOffsetT = 4;
        pub const VT_RESULT_JSON: ::flatbuffers::VOffsetT = 6;
        pub const VT_BINARY_ARTIFACT: ::flatbuffers::VOffsetT = 8;
        pub const VT_ERROR_MESSAGE: ::flatbuffers::VOffsetT = 10;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            PluginResponse { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args PluginResponseArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<PluginResponse<'bldr>> {
            let mut builder = PluginResponseBuilder::new(_fbb);
            if let Some(x) = args.error_message {
                builder.add_error_message(x);
            }
            if let Some(x) = args.binary_artifact {
                builder.add_binary_artifact(x);
            }
            if let Some(x) = args.result_json {
                builder.add_result_json(x);
            }
            builder.add_success(args.success);
            builder.finish()
        }

        #[inline]
        pub fn success(&self) -> bool {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<bool>(PluginResponse::VT_SUCCESS, Some(false))
                    .unwrap()
            }
        }
        /// A JSON string returned to the LLM context
        #[inline]
        pub fn result_json(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                    PluginResponse::VT_RESULT_JSON,
                    None,
                )
            }
        }
        /// Optional binary artifact generated by the plugin (e.g., an altered image)
        #[inline]
        pub fn binary_artifact(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                        PluginResponse::VT_BINARY_ARTIFACT,
                        None,
                    )
            }
        }
        /// If success=false, provide the error here
        #[inline]
        pub fn error_message(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                    PluginResponse::VT_ERROR_MESSAGE,
                    None,
                )
            }
        }
    }

    impl ::flatbuffers::Verifiable for PluginResponse<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<bool>("success", Self::VT_SUCCESS, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                    "result_json",
                    Self::VT_RESULT_JSON,
                    false,
                )?
                .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                    "binary_artifact",
                    Self::VT_BINARY_ARTIFACT,
                    false,
                )?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                    "error_message",
                    Self::VT_ERROR_MESSAGE,
                    false,
                )?
                .finish();
            Ok(())
        }
    }
    pub struct PluginResponseArgs<'a> {
        pub success: bool,
        pub result_json: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub binary_artifact: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
        pub error_message: Option<::flatbuffers::WIPOffset<&'a str>>,
    }
    impl<'a> Default for PluginResponseArgs<'a> {
        #[inline]
        fn default() -> Self {
            PluginResponseArgs {
                success: false,
                result_json: None,
                binary_artifact: None,
                error_message: None,
            }
        }
    }

    pub struct PluginResponseBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PluginResponseBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_success(&mut self, success: bool) {
            self.fbb_
                .push_slot::<bool>(PluginResponse::VT_SUCCESS, success, false);
        }
        #[inline]
        pub fn add_result_json(&mut self, result_json: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                PluginResponse::VT_RESULT_JSON,
                result_json,
            );
        }
        #[inline]
        pub fn add_binary_artifact(
            &mut self,
            binary_artifact: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
        ) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                PluginResponse::VT_BINARY_ARTIFACT,
                binary_artifact,
            );
        }
        #[inline]
        pub fn add_error_message(&mut self, error_message: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                PluginResponse::VT_ERROR_MESSAGE,
                error_message,
            );
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> PluginResponseBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            PluginResponseBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<PluginResponse<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for PluginResponse<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("PluginResponse");
            ds.field("success", &self.success());
            ds.field("result_json", &self.result_json());
            ds.field("binary_artifact", &self.binary_artifact());
            ds.field("error_message", &self.error_message());
            ds.finish()
        }
    }
    pub enum PluginManifestOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct PluginManifest<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for PluginManifest<'a> {
        type Inner = PluginManifest<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> PluginManifest<'a> {
        pub const VT_NAME: ::flatbuffers::VOffsetT = 4;
        pub const VT_DESCRIPTION: ::flatbuffers::VOffsetT = 6;
        pub const VT_TOOLS_JSON: ::flatbuffers::VOffsetT = 8;
        pub const VT_CAPABILITIES: ::flatbuffers::VOffsetT = 10;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            PluginManifest { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args PluginManifestArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<PluginManifest<'bldr>> {
            let mut builder = PluginManifestBuilder::new(_fbb);
            if let Some(x) = args.capabilities {
                builder.add_capabilities(x);
            }
            if let Some(x) = args.tools_json {
                builder.add_tools_json(x);
            }
            if let Some(x) = args.description {
                builder.add_description(x);
            }
            if let Some(x) = args.name {
                builder.add_name(x);
            }
            builder.finish()
        }

        /// The name of the skill
        #[inline]
        pub fn name(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<&str>>(PluginManifest::VT_NAME, None)
            }
        }
        /// The description of the skill for the LLM
        #[inline]
        pub fn description(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                    PluginManifest::VT_DESCRIPTION,
                    None,
                )
            }
        }
        /// A JSON schema describing all the tools this plugin provides
        #[inline]
        pub fn tools_json(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                    PluginManifest::VT_TOOLS_JSON,
                    None,
                )
            }
        }
        /// The host capabilities required by this plugin (e.g., "http:api.github.com", "fs:read")
        #[inline]
        pub fn capabilities(
            &self,
        ) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>,
                >>(PluginManifest::VT_CAPABILITIES, None)
            }
        }
    }

    impl ::flatbuffers::Verifiable for PluginManifest<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                    "description",
                    Self::VT_DESCRIPTION,
                    false,
                )?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                    "tools_json",
                    Self::VT_TOOLS_JSON,
                    false,
                )?
                .visit_field::<::flatbuffers::ForwardsUOffset<
                    ::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>,
                >>("capabilities", Self::VT_CAPABILITIES, false)?
                .finish();
            Ok(())
        }
    }
    pub struct PluginManifestArgs<'a> {
        pub name: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub description: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub tools_json: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub capabilities: Option<
            ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>,
            >,
        >,
    }
    impl<'a> Default for PluginManifestArgs<'a> {
        #[inline]
        fn default() -> Self {
            PluginManifestArgs {
                name: None,
                description: None,
                tools_json: None,
                capabilities: None,
            }
        }
    }

    pub struct PluginManifestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PluginManifestBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_name(&mut self, name: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(PluginManifest::VT_NAME, name);
        }
        #[inline]
        pub fn add_description(&mut self, description: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                PluginManifest::VT_DESCRIPTION,
                description,
            );
        }
        #[inline]
        pub fn add_tools_json(&mut self, tools_json: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                PluginManifest::VT_TOOLS_JSON,
                tools_json,
            );
        }
        #[inline]
        pub fn add_capabilities(
            &mut self,
            capabilities: ::flatbuffers::WIPOffset<
                ::flatbuffers::Vector<'b, ::flatbuffers::ForwardsUOffset<&'b str>>,
            >,
        ) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                PluginManifest::VT_CAPABILITIES,
                capabilities,
            );
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> PluginManifestBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            PluginManifestBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<PluginManifest<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for PluginManifest<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("PluginManifest");
            ds.field("name", &self.name());
            ds.field("description", &self.description());
            ds.field("tools_json", &self.tools_json());
            ds.field("capabilities", &self.capabilities());
            ds.finish()
        }
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a `PluginRequest`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_plugin_request_unchecked`.
    pub fn root_as_plugin_request(
        buf: &[u8],
    ) -> Result<PluginRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root::<PluginRequest>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `PluginRequest` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_plugin_request_unchecked`.
    pub fn size_prefixed_root_as_plugin_request(
        buf: &[u8],
    ) -> Result<PluginRequest<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root::<PluginRequest>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `PluginRequest` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_plugin_request_unchecked`.
    pub fn root_as_plugin_request_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<PluginRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root_with_opts::<PluginRequest<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `PluginRequest` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_plugin_request_unchecked`.
    pub fn size_prefixed_root_as_plugin_request_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<PluginRequest<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root_with_opts::<PluginRequest<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a PluginRequest and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `PluginRequest`.
    pub unsafe fn root_as_plugin_request_unchecked(buf: &[u8]) -> PluginRequest<'_> {
        unsafe { ::flatbuffers::root_unchecked::<PluginRequest>(buf) }
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed PluginRequest and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `PluginRequest`.
    pub unsafe fn size_prefixed_root_as_plugin_request_unchecked(buf: &[u8]) -> PluginRequest<'_> {
        unsafe { ::flatbuffers::size_prefixed_root_unchecked::<PluginRequest>(buf) }
    }
    #[inline]
    pub fn finish_plugin_request_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<PluginRequest<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_plugin_request_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<PluginRequest<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
} // pub mod swarmclaw_plugin
